### ISSUE TITLE
Demo app fails with Node 18

### ISSUE THREAD

**Issue by JakobMiksch** [camptocamp/ogc-client#10]
when I run the demo app with Node 18 it fails with this error:

```

> ogc-client-app@0.1.0 serve
> vue-cli-service serve

 INFO  Starting development server...
10% building 2/5 modules 3 active ...ksch/Code/ogc-client/app/node_modules/babel-loader/lib/index.js!/mnt/c/Users/johndoe/Code/ogc-client/app/src/main.js n
ode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/mnt/c/Users/johndoe/Code/ogc-client/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/mnt/c/Users/johndoe/Code/ogc-client/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/mnt/c/Users/johndoe/Code/ogc-client/app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /mnt/c/Users/johndoe/Code/ogc-client/app/node_modules/webpack/lib/NormalModule.js:503:5
    at /mnt/c/Users/johndoe/Code/ogc-client/app/node_modules/webpack/lib/NormalModule.js:358:12
    at /mnt/c/Users/johndoe/Code/ogc-client/app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/mnt/c/Users/johndoe/Code/ogc-client/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/mnt/c/Users/johndoe/Code/ogc-client/app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/mnt/c/Users/johndoe/Code/ogc-client/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /mnt/c/Users/johndoe/Code/ogc-client/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /mnt/c/Users/johndoe/Code/ogc-client/app/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
```

It works with Node 16 for me

**Comment by jahow** [comment]
Thanks for the report! Indeed some dependencies seem a little bit out of date here... I'll upgrade those!

**Comment by jahow** [comment]
This should be fixed on main, albeit with a workaround. A definitive solution would imply upgrading all the vue-related libs to their latest major versions.
