### ISSUE TITLE
Vue3 - ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by JakobMiksch** [camptocamp/ogc-client#20]
In a Vue3 application using Node 20 I get this error.

Do you a hint what the problem could be?

```
Uncaught ReferenceError: exports is not defined
    at node_modules/@camptocamp/ogc-client/dist/worker/index.js (index.js:2:23)
    at __init (chunk-GFT2G5UO.js?v=951b9568:15:56)
    at node_modules/@camptocamp/ogc-client/dist/wfs/endpoint.js (endpoint.js:3:16)
    at __require2 (chunk-GFT2G5UO.js?v=951b9568:18:50)
    at node_modules/@camptocamp/ogc-client/dist/index.js (index.js:4:18)
    at __require2 (chunk-GFT2G5UO.js?v=951b9568:18:50)
    at index.js:16:1
```

or as screenshot of the browser console

![image](https://github.com/camptocamp/ogc-client/assets/15704517/f569e196-fcbf-458f-a0e4-9fc4c45d5d3c)

**Comment by jahow** [comment]
@JakobMiksch the worker wasn't serialized any more in the published script, this should be fixed; could you please confirm this is fixed in the main branch? thanks so much for your continued support!

**Comment by JakobMiksch** [comment]
yes, now I can run the functions. Great, thanks for the fix!

**Comment by JakobMiksch** [comment]
I am closing
